source 'http://rubygems.org/'
gem 'rails', '2.3.14'
gem 'mysql'

gem 'rake', '0.9.2.2'
gem 'haml', '~> 3.0.6'
gem 'libxml-ruby', :require => 'libxml'
gem 'libxslt-ruby', '0.9.2', :require => 'libxslt'
gem 'rubyzip', :require => 'zip/zip'
gem 'mime-types', :require => 'mime/types'
gem 'uuidtools', '1.0.4'
gem 'will_paginate', '~> 2.3.16'
gem 'whenever', '0.4.1', :require => false
gem 'rsolr', '0.12.1'
gem 'sunspot', '1.1.0'
gem 'sunspot_rails', '1.1.0', :require => 'sunspot/rails'
gem 'grit'
gem 'aws-s3', :require => 'aws/s3'
gem 'delayed_job', '< 2'
gem 'fastercsv'
gem 'formtastic', '1.2.4'
gem 'exceptional', :group => :production
