class FormatDigitalsController < PicklistsController
  def set_standard_pbcore
    @standard_pbcore =
      [
       "not specified", "video/3gpp", "video/3gpp2", "video/3gpp-tt",
       "video/BMPEG", "video/BT656", "video/CelB", "video/DV",
       "video/H261", "video/H263", "video/H263-1998", "video/H263-2000",
       "video/H264", "video/JPEG", "video/MJ2", "video/MP1S",
       "video/MP2P", "video/MP2T", "video/mp4", "video/MP4V-ES",
       "video/MPV", "video/mpeg", "video/mpeg4-generic", "video/nv",
       "video/parityfec", "video/pointer", "video/quicktime",
       "video/raw", "video/rtx", "video/SMPTE292M", "video/vc1",
       "video/vnd.dlna.mpeg-tts", "video/vnd.fvt",
       "video/vnd.hns.video", "video/vnd.motorola.video",
       "video/vnd.motorola.videop", "video/vnd.mpegurl",
       "video/vnd.nokia.interleaved-multimedia",
       "video/vnd.nokia.videovoip", "video/vnd.objectvideo",
       "video/vnd.sealed.mpeg1", "video/vnd.sealed.mpeg4",
       "video/vnd.sealed.swf", "video/vnd.sealedmedia.softseal.mov",
       "video/vnd.vivo", "audio/32kadpcm", "audio/3gpp", "audio/3gpp2",
       "audio/ac3", "audio/AMR", "audio/AMR-WB", "audio/amr-wb+",
       "audio/asc", "audio/basic", "audio/BV16", "audio/BV32",
       "audio/clearmode", "audio/CN", "audio/DAT12", "audio/dls",
       "audio/dsr-es201108", "audio/dsr-es202050", "audio/dsr-es202211",
       "audio/dsr-es202212", "audio/eac3", "audio/DVI4", "audio/EVRC",
       "audio/EVRC0", "audio/EVRC1", "audio/EVRCB", "audio/EVRCB0",
       "audio/EVRCB1", "audio/EVRC-QCP", "audio/G722", "audio/G7221",
       "audio/G723", "audio/G726-16", "audio/G726-24", "audio/G726-32",
       "audio/G726-40", "audio/G728", "audio/G729", "audio/G7291",
       "audio/G729D", "audio/G729E", "audio/GSM", "audio/GSM-EFR",
       "audio/iLBC", "audio/L8", "audio/L16", "audio/L20", "audio/L24",
       "audio/LPC", "audio/mobile-xmf", "audio/MPA", "audio/mp4",
       "audio/MP4A-LATM", "audio/mpa-robust", "audio/mpeg",
       "audio/mpeg4-generic", "audio/parityfec", "audio/PCMA",
       "audio/PCMU", "audio/prs.sid", "audio/QCELP", "audio/RED",
       "audio/rtp-midi", "audio/rtx", "audio/SMV", "audio/SMV0",
       "audio/SMV-QCP", "audio/t140c", "audio/t38",
       "audio/telephone-event", "audio/tone", "audio/VDVI",
       "audio/VMR-WB", "audio/vnd.3gpp.iufp", "audio/vnd.4SB",
       "audio/vnd.audiokoz", "audio/vnd.CELP", "audio/vnd.cisco.nse",
       "audio/vnd.cmles.radio-events", "audio/vnd.cns.anp1",
       "audio/vnd.cns.inf1", "audio/vnd.digital-winds",
       "audio/vnd.dlna.adts", "audio/vnd.everad.plj",
       "audio/vnd.hns.audio", "audio/vnd.lucent.voice",
       "audio/vnd.nokia.mobile-xmf", "audio/vnd.nortel.vbk",
       "audio/vnd.nuera.ecelp4800", "audio/vnd.nuera.ecelp7470",
       "audio/vnd.nuera.ecelp9600", "audio/vnd.octel.sbc",
       "audio/vnd.rhetorex.32kadpcm",
       "audio/vnd.sealedmedia.softseal.mpeg", "audio/vnd.vmx.cvsd",
       "image/cgm", "image/fits", "image/g3fax", "image/gif",
       "image/ief", "image/jp2", "image/jpeg", "image/jpm", "image/jpx",
       "image/naplps", "image/png", "image/prs.btif", "image/prs.pti",
       "image/t38", "image/tiff", "image/tiff-fx",
       "image/vnd.adobe.photoshop", "image/vnd.cns.inf2",
       "image/vnd.djvu", "image/vnd.dwg", "image/vnd.dxf",
       "image/vnd.fastbidsheet", "image/vnd.fpx", "image/vnd.fst",
       "image/vnd.fujixerox.edmics-mmr",
       "image/vnd.fujixerox.edmics-rlc", "image/vnd.globalgraphics.pgb",
       "image/vnd.microsoft.icon", "image/vnd.mix", "image/vnd.ms-modi",
       "image/vnd.net-fpx", "image/vnd.sealed.png",
       "image/vnd.sealedmedia.softseal.gif",
       "image/vnd.sealedmedia.softseal.jpg", "image/vnd.svf",
       "image/vnd.wap.wbmp", "image/vnd.xiff", "text/calendar",
       "text/css", "text/csv", "text/directory", "text/dns",
       "text/ecmascript (obsolete)", "text/enriched", "text/html",
       "text/javascript (obsolete)", "text/parityfec", "text/plain",
       "text/prs.fallenstein.rst", "text/prs.lines.tag", "text/RED",
       "text/rfc822-headers", "text/richtext", "text/rtf", "text/rtx",
       "text/sgml", "text/t140", "text/tab-separated-values",
       "text/troff", "text/uri-list", "text/vnd.abc", "text/vnd.curl",
       "text/vnd.DMClientScript", "text/vnd.esmertec.theme-descriptor",
       "text/vnd.fly", "text/vnd.fmi.flexstor", "text/vnd.in3d.3dml",
       "text/vnd.in3d.spot", "text/vnd.IPTC.NewsML",
       "text/vnd.IPTC.NITF", "text/vnd.latex-z",
       "text/vnd.motorola.reflex", "text/vnd.ms-mediapackage",
       "text/vnd.net2phone.commcenter.command",
       "text/vnd.sun.j2me.app-descriptor",
       "text/vnd.trolltech.linguist", "text/vnd.wap.si",
       "text/vnd.wap.sl", "text/vnd.wap.wml", "text/vnd.wap.wmlscript",
       "text/xml", "text/xml-external-parsed-entity",
       "application/http", "application/hyperstudio",
       "application/javascript", "application/mac-binhex40",
       "application/marc", "application/mbox",
       "application/mediaservercontrol+xml", "application/mp4",
       "application/mpeg4-generic", "application/mpeg4-iod",
       "application/mpeg4-iod-xmt", "application/msword",
       "application/mxf", "application/pdf", "application/postscript",
       "application/rdf+xml", "application/rtf", "application/rtx",
       "application/sgml", "application/sgml-open-catalog",
       "application/smil (OBSOLETE)", "application/smil+xml",
       "application/soap+fastinfoset", "application/soap+xml",
       "application/ssml+xml", "application/vnd.adobe.xfdf",
       "application/vnd.apple.installer+xml",
       "application/vnd.framemaker",
       "application/vnd.google-earth.kml+xml",
       "application/vnd.google-earth.kmz",
       "application/vnd.HandHeld-Entertainment+xml",
       "application/vnd.lotus-1-2-3", "application/vnd.lotus-approach",
       "application/vnd.lotus-freelance", "application/vnd.lotus-notes",
       "application/vnd.lotus-organizer",
       "application/vnd.lotus-screencam",
       "application/vnd.lotus-wordpro",
       "application/vnd.mozilla.xul+xml", "application/vnd.ms-artgalry",
       "application/vnd.ms-asf", "application/vnd.ms-cab-compressed",
       "application/vnd.mseq", "application/vnd.ms-excel",
       "application/vnd.ms-fontobject", "application/vnd.ms-htmlhelp",
       "application/vnd.msign", "application/vnd.ms-ims",
       "application/vnd.ms-lrm", "application/vnd.ms-powerpoint",
       "application/vnd.ms-project", "application/vnd.ms-tnef",
       "application/vnd.ms-wmdrm.lic-chlg-req",
       "application/vnd.ms-wmdrm.lic-resp",
       "application/vnd.ms-wmdrm.meter-chlg-req",
       "application/vnd.ms-wmdrm.meter-resp",
       "application/vnd.ms-works", "application/vnd.ms-wpl",
       "application/vnd.ms-xpsdocument", "application/vnd.palm",
       "application/vnd.paos.xml", "application/vnd.Quark.QuarkXPress",
       "application/vnd.visio", "application/vnd.wordperfect",
       "application/wordperfect5.1", "application/xhtml+xml",
       "application/xml", "application/xml-dtd",
       "application/xml-external-parsed-entity", "application/zip"
      ].to_set.freeze
  end
end
